export type MissionStatus = 'Completed' | 'Upcoming' | 'Unsuccessful';
export type Payload = { name: string; purpose: string; category: string; result?: string };
export type Mission = {
  id: string; name: string; provider: string; lander: string; status: MissionStatus; statusDetail: string;
  launch: string | null; landing: string | null; plannedWindow?: string;
  region: string; actualLocation: string | null; coordinates: { latitude: number; longitude: number; kind: 'actual' | 'planned'; source: string } | null;
  summary: string; objectives: string[]; outcome: string; results: string[]; payloadCount: number | null; payloadCountNote?: string;
  payloads: Payload[]; sources: { title: string; url: string }[]; verified: string;
};
const science = 'https://science.nasa.gov/lunar-science/clps-deliveries/';
const providers = 'https://www.nasa.gov/commercial-lunar-payload-services/clps-providers/';
const p = (name: string, purpose: string, category: string, result?: string): Payload => ({name,purpose,category,result});
export const missions: Mission[] = [
  { id:'peregrine-1', name:'Peregrine Mission One', provider:'Astrobotic', lander:'Peregrine', status:'Unsuccessful', statusDetail:'Lunar delivery not achieved', launch:'2024-01-08', landing:null,
    region:'Sinus Viscositatis', actualLocation:null, coordinates:null,
    summary:'The first CLPS launch carried five NASA payloads but did not reach the lunar surface.',
    objectives:['Investigate lunar volatiles, radiation and surface composition.'],
    outcome:'A spacecraft anomaly prevented a lunar landing. Peregrine re-entered Earth’s atmosphere on January 18, 2024.', results:['No lunar surface measurements.'], payloadCount:5,
    payloads:[p('LRA · Laser Retroreflector Array','Provide a passive laser-ranging reference.','Navigation'),p('NSS · Neutron Spectrometer System','Investigate subsurface hydrogen.','Volatiles'),p('LETS · Linear Energy Transfer Spectrometer','Measure the radiation environment.','Radiation'),p('NIRVSS · Near Infrared Volatiles Spectrometer System','Examine surface composition and volatiles.','Volatiles'),p('PITMS · Peregrine Ion-Trap Mass Spectrometer','Identify gases around the lander.','Exosphere')],
    sources:[{title:'NASA: Peregrine science manifest',url:science+'to2-astrobotic/'},{title:'NASA: delivery records',url:science},{title:'NASA: delivery providers and outcomes',url:providers}],verified:'2026-10-08' },
  { id:'im-1', name:'IM-1 · Odysseus', provider:'Intuitive Machines', lander:'Nova-C / Odysseus', status:'Completed', statusDetail:'Completed with landing limitations', launch:'2024-02-15', landing:'2024-02-22', region:'Malapert A', actualLocation:'Near Malapert A, south polar region',
    coordinates:{latitude:-80.13,longitude:1.44,kind:'actual',source:'https://lroc.im-ldi.com/images/1360'},
    summary:'Odysseus delivered six NASA payloads near the lunar south pole.', objectives:['Demonstrate navigation and characterize the near-surface environment.'], outcome:'The lander tipped over after touchdown and operated on the surface. Completed does not mean every objective was achieved.',results:['NASA received science and technology data despite the lander’s tilted position.'],payloadCount:6,
    payloads:[p('LN-1 · Lunar Node 1','Test radio navigation between lunar assets.','Navigation'),p('SCALPSS · Stereo Cameras for Lunar Plume-Surface Studies','Observe exhaust interacting with the ground.','Surface'),p('ROLSES · Radio-wave Observations at the Lunar Surface of the photoElectron Sheath','Investigate radio and plasma conditions.','Plasma'),p('NDL · Navigation Doppler Lidar','Measure descent velocity and altitude.','Navigation'),p('LRA · Laser Retroreflector Array','Provide a laser-ranging reference.','Navigation'),p('RFMG · Radio Frequency Mass Gauge','Measure propellant quantity.','Technology')],
    sources:[{title:'NASA: IM-1 science payloads',url:science+'to2-im/'},{title:'NASA: delivery records',url:science},{title:'NASA: providers and outcomes',url:providers},{title:'LRO Camera team: observed landing coordinates',url:'https://lroc.im-ldi.com/images/1360'}],verified:'2026-10-08' },
  { id:'blue-ghost-1', name:'Blue Ghost Mission 1', provider:'Firefly Aerospace', lander:'Blue Ghost', status:'Completed', statusDetail:'Surface mission concluded', launch:'2025-01-15', landing:'2025-03-02', region:'Mare Crisium', actualLocation:'Mare Crisium', coordinates:null,
    summary:'Ten NASA investigations explored a volcanic plain on the Moon’s near side.',objectives:['Study regolith, the lunar interior and technologies for future exploration.'],outcome:'Landed upright on March 2 and concluded surface operations on March 16, 2025.',results:['LuGRE acquired navigation signals on the lunar surface.','Electrodynamic Dust Shield demonstrated removal of lunar dust.'],payloadCount:10,
    payloads:[p('NGLR · Next Generation Lunar Retroreflector','Enable precise Earth–Moon laser ranging.','Navigation'),p('RadPC · Radiation Tolerant Computer','Test computing in space radiation.','Technology'),p('RAC · Regolith Adherence Characterization','Study dust sticking to materials.','Surface'),p('LMS · Lunar Magnetotelluric Sounder','Probe the Moon’s interior electromagnetically.','Geophysics'),p('LEXI · Lunar Environment heliospheric X-ray Imager','Observe Earth’s magnetosphere.','Heliophysics'),p('LPV · Lunar PlanetVac','Test pneumatic soil collection.','Technology'),p('LISTER · Lunar Instrumentation for Subsurface Thermal Exploration with Rapidity','Investigate subsurface heat flow.','Geophysics'),p('SCALPSS 1.1 · Stereo Cameras for Lunar Plume-Surface Studies','Image landing-plume effects.','Surface'),p('EDS · Electrodynamic Dust Shield','Remove dust using electric fields.','Technology','Demonstrated dust removal.'),p('LuGRE · Lunar GNSS Receiver Experiment','Test GPS and Galileo navigation at the Moon.','Navigation','Acquired navigation signals on the surface.')],
    sources:[{title:'NASA: Blue Ghost science manifest',url:science+'to19d-firefly/'},{title:'NASA: mission conclusion and initial results',url:'https://www.nasa.gov/news-release/nasa-science-continues-after-fireflys-first-moon-mission-concludes/'},{title:'NASA: landing and launch information',url:'https://www.nasa.gov/news-release/touchdown-carrying-nasa-science-fireflys-blue-ghost-lands-on-moon/'}],verified:'2026-10-08' },
  { id:'im-2', name:'IM-2 · Athena', provider:'Intuitive Machines', lander:'Nova-C / Athena', status:'Unsuccessful', statusDetail:'Surface mission ended early; some data returned', launch:'2025-02-27', landing:'2025-03-06', region:'Mons Mouton', actualLocation:'Crater in the Mons Mouton region', coordinates:{latitude:-84.79,longitude:29.20,kind:'actual',source:'https://pds.nasa.gov/ds-view/pds/viewContext.jsp?identifier=urn:nasa:pds:context:instrument_host:spacecraft.clps_to_prime1_athena&version=1.0'},
    summary:'Athena carried a drill and mass spectrometer to investigate resources near the south pole.',objectives:['Demonstrate drilling and search for volatile gases.'],outcome:'Landed on its side. Operations ended March 7, 2025 before the full surface investigation could be performed.',results:['TRIDENT demonstrated its range of motion but could not reach the surface.'],payloadCount:3,payloadCountNote:'Three instruments: the two-instrument PRIME-1 suite plus LRA; not three independent suites.',
    payloads:[p('TRIDENT · The Regolith and Ice Drill for Exploring New Terrain','Bring subsurface material up for analysis.','Volatiles','Could not reach the surface.'),p('MSOLO · Mass Spectrometer Observing Lunar Operations','Identify and quantify gases.','Volatiles'),p('LRA · Laser Retroreflector Array','Provide a laser-ranging reference.','Navigation')],sources:[{title:'NASA: IM-2 outcome',url:'https://www.nasa.gov/news-release/nasa-receives-some-data-before-intuitive-machines-ends-lunar-mission/'},{title:'NASA: PRIME-1 science',url:science+'prime-1-im/'},{title:'NASA PDS: UTC launch, location and instruments',url:'https://pds.nasa.gov/ds-view/pds/viewContext.jsp?identifier=urn:nasa:pds:context:instrument_host:spacecraft.clps_to_prime1_athena&version=1.0'}],verified:'2026-10-08' },
  { id:'im-3',name:'IM-3',provider:'Intuitive Machines',lander:'Nova-C',status:'Upcoming',statusDetail:'Planned delivery; schedule subject to change',launch:null,landing:null,plannedWindow:'2026 planning window in NASA source; exact date unconfirmed',region:'Reiner Gamma',actualLocation:null,coordinates:null,
    summary:'A planned delivery to a lunar swirl will investigate magnetism and autonomous exploration.',objectives:['Study the relationship between magnetic anomalies and lunar swirls.','Demonstrate cooperative robotic exploration.'],outcome:'No completed delivery confirmed in the reviewed sources.',results:[],payloadCount:4,payloads:[p('Lunar Vertex','Study lunar magnetic anomalies and swirls.','Geophysics'),p('CADRE · Cooperative Autonomous Distributed Robotic Exploration','Test cooperating autonomous rovers.','Robotics'),p('MoonLIGHT Pointing Actuator','Support precision laser ranging.','Navigation'),p('LUSEM · Lunar Space Environment Monitor','Study charged particles near the surface.','Radiation')],sources:[{title:'NASA: CP-11 planned mission and payloads',url:science+'cp-11/'}],verified:'2026-10-08' }
];
export function filterMissions(query: string, status = 'All', provider = 'All') {
  const terms = query.toLocaleLowerCase().trim().split(/\s+/).filter(Boolean);
  return missions.filter(m => (status === 'All' || m.status === status) && (provider === 'All' || m.provider === provider) && terms.every(t => [m.name,m.provider,m.lander,m.status,m.region,...m.payloads.map(p=>p.name)].join(' ').toLocaleLowerCase().includes(t)));
}
export function timelineMissions(records = missions) { return [...records].sort((a,b)=>(a.launch ?? '9999').localeCompare(b.launch ?? '9999')); }
export function formatDate(date: string | null) { return date ? new Date(date+'T12:00:00Z').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'}) : 'Not confirmed'; }

