'use client';
import dynamic from 'next/dynamic';
import Link from 'next/link';
import { useMemo, useRef, useState } from 'react';
import { missions, filterMissions, timelineMissions, formatDate, type Mission } from '@/lib/missions';
const Globe = dynamic(()=>import('@/components/LunarGlobe'),{ssr:false,loading:()=> <div className="globe-canvas model-message">Initializing lunar viewport…</div>});
const PlanningPanel = dynamic(()=>import('@/components/PlanningPanel'));
type Section = 'planner' | 'explorer' | 'timeline' | 'payloads' | 'compare';
const tabs: [Section,string][] = [['planner','Site & Date Planner'],['explorer','Mission Explorer'],['timeline','Timeline'],['payloads','Payload Explorer'],['compare','Compare Missions']];
function Status({mission}:{mission:Mission}){return <span className={`mission-status ${mission.status.toLowerCase()}`}>{mission.status}</span>}
function Details({mission:m,onClose}:{mission:Mission;onClose:()=>void}) {
  return <aside id="selected-mission-brief" className="mission-detail" aria-label="Mission details" onKeyDown={e=>{if(e.key==='Escape')onClose()}}>
    <div className="detail-top"><span>MISSION BRIEF</span><button aria-label="Close mission details" onClick={onClose}>×</button></div>
    <Status mission={m}/><h2>{m.name}</h2><p className="mission-provider">{m.provider} / {m.lander}</p><p>{m.summary}</p><p className="status-detail">{m.statusDetail}</p>
    <dl><div><dt>Launch · UTC</dt><dd>{formatDate(m.launch)}</dd></div><div><dt>Lunar touchdown · UTC</dt><dd>{m.landing?formatDate(m.landing):m.status==='Unsuccessful'?'Did not land':'Not confirmed'}</dd></div><div><dt>Planned landing region</dt><dd>{m.region}</dd></div><div><dt>Confirmed landing location</dt><dd>{m.actualLocation??'None confirmed'}</dd></div></dl>
    {m.plannedWindow&&<p className="status-detail">{m.plannedWindow}</p>}
    <div className="location-evidence"><h3>Location evidence</h3>{m.coordinates?<><p>{Math.abs(m.coordinates.latitude).toFixed(2)}° {m.coordinates.latitude<0?'S':'N'} / {Math.abs(m.coordinates.longitude).toFixed(2)}° {m.coordinates.longitude<0?'W':'E'} · {m.coordinates.kind} site</p><a target="_blank" rel="noreferrer" href={m.coordinates.source}>Coordinate source ↗</a></>:<p>Precise coordinates are not verified in this dataset.</p>}<p>{m.coordinates?'Select Focus selected location below the Moon to view this site.':'Location focus requires sourced coordinates.'}</p></div>
    <h3>Scientific objectives</h3><ul>{m.objectives.map(t=><li key={t}>{t}</li>)}</ul><h3>Mission outcome</h3><p>{m.outcome}</p><h3>Reported results</h3>{m.results.length?<ul>{m.results.map(t=><li key={t}>{t}</li>)}</ul>:<p>No results available for this planned mission.</p>}
    <h3>Payloads & instruments <span className="count">{m.payloadCount??' - '}</span></h3>{m.payloadCountNote&&<p>{m.payloadCountNote}</p>}{m.payloads.map(p=><details key={p.name}><summary>{p.name}</summary><p>{p.purpose}</p><small>{p.category}</small><p>{p.result??'Individual results not summarized in this dataset.'}</p></details>)}
    <h3>Sources & verification</h3><div className="mission-sources">{m.sources.map(s=><a key={s.url} href={s.url} target="_blank" rel="noreferrer">{s.title} ↗</a>)}</div><p className="verified-date">Source review: {m.verified}. Curated snapshot; schedules may change.</p>
  </aside>;
}
export default function Home(){
  const [section,setSection]=useState<Section>('planner'),[query,setQuery]=useState(''),[status,setStatus]=useState('All'),[provider,setProvider]=useState('All');
  const [selectedId,setSelected]=useState<string|null>('blue-ghost-1'),[reset,setReset]=useState(0),[a,setA]=useState('blue-ghost-1'),[b,setB]=useState('im-1'),[payloadQuery,setPayloadQuery]=useState('');
  const mainRef=useRef<HTMLElement>(null);
  const visible=useMemo(()=>filterMissions(query,status,provider),[query,status,provider]);
  const globeLocations=useMemo(()=>visible.flatMap(m=>m.coordinates?[{id:m.id,name:m.name,...m.coordinates}]:[]),[visible]);
  const selected=missions.find(m=>m.id===selectedId), first=missions.find(m=>m.id===a)!, second=missions.find(m=>m.id===b)!;
  const select=(id:string)=>{setSelected(id); if(window.innerWidth<=700)requestAnimationFrame(()=>document.getElementById('selected-mission-brief')?.scrollIntoView({block:'start'}));};
  const openMission=(id:string)=>{select(id);setSection('explorer');if(window.innerWidth>700)mainRef.current?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});};
  const clear=()=>{setQuery('');setStatus('All');setProvider('All');};
  const payloads=visible.flatMap(m=>m.payloads.map(p=>({...p,mission:m}))).filter(p=>(p.name+' '+p.purpose+' '+p.category).toLowerCase().includes(payloadQuery.toLowerCase()));
  return <main className="clps-app" ref={mainRef}>
    <a className="skip-link" href="#mission-content">Skip to mission content</a>
    <header className="clps-header"><Link href="/" className="clps-brand"><span className="lunar-logo">◐</span><span>LUNARIS<small>CLPS LUNAR MISSION BROWSER</small></span></Link><nav aria-label="Mission navigation">{tabs.map(([id,label])=><button key={id} aria-pressed={section===id} onClick={()=>{setSection(id);requestAnimationFrame(()=>document.getElementById(id==='explorer'?'mission-content':'exploration-section')?.scrollIntoView({block:'start'}));}}>{label}</button>)}</nav><button className="header-reset" onClick={()=>setReset(n=>n+1)}>↺ Reset Moon</button></header>
    <div className="mission-intro"><div><p className="eyebrow">COMMERCIAL LUNAR PAYLOAD SERVICES</p><h1>Explore the Moon. Plan with evidence.</h1><p>Compare south-pole sites and dates, then explore the missions advancing lunar science.</p></div><div className="catalog-stat"><b>{missions.length.toString().padStart(2,'0')}</b><span>CURATED MISSIONS<br/>NASA sources · reviewed Oct 8, 2026</span></div></div>
    <div className="mission-workspace" id="mission-content">
      <aside className="mission-browser" aria-label="Mission browser"><div className="browser-title"><h2>Mission catalog</h2><span>{visible.length} / {missions.length}</span></div><label htmlFor="mission-search">Search missions</label><input id="mission-search" type="search" placeholder="Mission, region, instrument…" value={query} onChange={e=>setQuery(e.target.value)}/><div className="filter-pair"><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}>{['All','Completed','Upcoming','Unsuccessful'].map(s=><option key={s}>{s}</option>)}</select></label><label>Provider<select value={provider} onChange={e=>setProvider(e.target.value)}><option>All</option>{[...new Set(missions.map(m=>m.provider))].map(s=><option key={s}>{s}</option>)}</select></label></div><p className="filter-info" role="status">{visible.length} matching missions</p>
        <div className="mission-list">{visible.map((m,i)=><button className="mission-card" key={m.id} aria-pressed={m.id===selectedId} onClick={()=>select(m.id)}><span className="card-index">{String(i+1).padStart(2,'0')} / <Status mission={m}/></span><b>{m.name}</b><span>{m.provider}</span><small>{m.region} <span aria-hidden="true">↗</span></small></button>)}{!visible.length&&<div className="empty-state"><b>No matching missions</b><p>Try another name, payload or provider.</p></div>}</div>
        {(query||status!=='All'||provider!=='All')&&<button className="clear-filters" onClick={clear}>Clear search & filters</button>}<p className="catalog-note">Status groups describe this catalog’s outcomes. “Completed” can include limitations. Read each mission brief.</p><Link className="terrain-link" href="/terrain">Explore NASA south-pole terrain ↗</Link>
      </aside>
      <div className="mission-center"><Globe reset={reset} locations={globeLocations} selectedId={selectedId} onSelect={select}/><div className="selected-strip" aria-live="polite"><span>SELECTED MISSION</span><b>{selected?.name??'Select a mission to read its brief'}</b>{selected&&!visible.some(m=>m.id===selected.id)&&<small>Outside current filters</small>}</div>
        <section id="exploration-section" className="exploration-section" aria-label={tabs.find(t=>t[0]===section)![1]}>
          {section==='planner'&&<PlanningPanel/>}
          {section==='explorer'&&<><p className="eyebrow">SCIENCE, DELIVERED.</p><h2>Different places. Different questions.</h2><p>NASA buys lunar delivery services from commercial companies through CLPS. Instruments investigate the Moon and test technologies for future exploration.</p><div className="science-stories"><article><span>01 / VOLATILES</span><h3>Resources near the poles</h3><p>PRIME-1 was designed to investigate subsurface material and gases near the south pole.</p></article><article><span>02 / GEOLOGY</span><h3>Inside a volcanic plain</h3><p>Blue Ghost’s Mare Crisium investigations examine regolith and the Moon’s interior.</p></article><article><span>03 / MAGNETISM</span><h3>The mystery of lunar swirls</h3><p>Lunar Vertex is planned to examine magnetic anomalies at Reiner Gamma.</p></article></div><a href="https://www.nasa.gov/reference/commercial-lunar-payload-services/" target="_blank" rel="noreferrer">Explore NASA’s CLPS program ↗</a></>}
          {section==='timeline'&&<><p className="eyebrow">DELIVERY HISTORY</p><h2>Mission timeline</h2><p>Confirmed launch dates, in UTC. Planned missions follow separately. Catalog filters apply.</p><ol className="mission-timeline">{timelineMissions(visible).map(m=><li key={m.id}><button onClick={()=>openMission(m.id)}><time>{m.launch?formatDate(m.launch):'PLANNED · DATE UNCONFIRMED'}</time><b>{m.name}</b><Status mission={m}/><span>{m.landing?`Touchdown: ${formatDate(m.landing)}`:m.plannedWindow??'No lunar touchdown'}</span></button></li>)}</ol>{!visible.length&&<p>No missions match the catalog filters.</p>}</>}
          {section==='payloads'&&<><p className="eyebrow">INSTRUMENT DIRECTORY</p><h2>NASA payload explorer</h2><label htmlFor="payload-search">Search payload names, purposes or categories</label><input id="payload-search" type="search" value={payloadQuery} onChange={e=>setPayloadQuery(e.target.value)} placeholder="Try navigation or TRIDENT"/><p>{payloads.length} instruments / payloads across matching missions. Includes international contributions to CLPS manifests.</p><div className="payload-grid">{payloads.map(p=><article key={p.mission.id+p.name}><span>{p.category}</span><h3>{p.name}</h3><p>{p.purpose}</p><p className="payload-result">{p.result??'Results not summarized in this catalog.'}</p><button onClick={()=>openMission(p.mission.id)}>View {p.mission.name} ↗</button></article>)}</div>{!payloads.length&&<p>No payloads match. Adjust the payload search or mission filters.</p>}</>}
          {section==='compare'&&<><p className="eyebrow">SIDE BY SIDE</p><h2>Compare missions</h2><p>Compare any two catalog records. Instrument totals follow source conventions; suites can contain several instruments.</p><div className="compare-picks"><label>Mission A<select value={a} onChange={e=>{const id=e.target.value;if(id===b)setB(a);setA(id)}}>{missions.map(m=><option value={m.id} key={m.id}>{m.name}</option>)}</select></label><label>Mission B<select value={b} onChange={e=>setB(e.target.value)}>{missions.filter(m=>m.id!==a).map(m=><option value={m.id} key={m.id}>{m.name}</option>)}</select></label></div><div className="mission-comparison"><table><caption>{first.name} vs {second.name}</caption><thead><tr><th>Field</th><th>{first.name}</th><th>{second.name}</th></tr></thead><tbody>{(['Provider','Status','Launch · UTC','Planned region','Actual location','NASA manifest count','Objectives','Outcome'] as const).map((label,i)=><tr key={label}><th scope="row">{label}</th>{[first,second].map(m=><td key={m.id}>{[m.provider,m.status+'  -  '+m.statusDetail,formatDate(m.launch),m.region,m.actualLocation??'None confirmed',`${m.payloadCount??'Unavailable'}${m.payloadCountNote?' · '+m.payloadCountNote:''}`,m.objectives.join(' '),m.outcome][i]}</td>)}</tr>)}</tbody></table></div><div className="comparison-links">{[first,second].map(m=><button key={m.id} onClick={()=>openMission(m.id)}>Open {m.name} brief ↗</button>)}</div></>}
        </section>
      </div>
      {selected?<Details key={selected.id} mission={selected} onClose={()=>setSelected(null)}/>:<aside className="mission-detail empty-state"><h2>Your mission brief</h2><p>Select a mission from the catalog, timeline or payload explorer.</p></aside>}
    </div>
    <footer className="clps-footer"><p>Independent educational project · Not affiliated with NASA. Selected missions, not a complete CLPS manifest.</p><p>3D “moon” by <a href="https://sketchfab.com/RenderX" target="_blank" rel="noreferrer">RenderX</a> · <a href="https://sketchfab.com/3d-models/moon-26cc0b7878bb4d919b68e2be399db466" target="_blank" rel="noreferrer">Sketchfab original</a> · <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noreferrer">CC BY 4.0</a>. Display centered and scaled; original geometry and texture preserved.</p></footer>
  </main>;
}
