'use client';
import { useState } from 'react';
import { sites } from '@/lib/sites';
import { type Ephemeris, type SkySample, aboveHorizonWindows, opportunityPercent, validateInterval } from '@/lib/ephemeris';
type Scenario={site:string;start:string;end:string};
const timeLabel=(time:string)=>new Date(time).toLocaleString('en-GB',{timeZone:'UTC',month:'short',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false});
function SkyChart({data,index,mask}:{data:Ephemeris;index:number;mask:number}){
  const sun=data.sun[index],earth=data.earth[index];const low=Math.min(-5,...data.sun.map(s=>s.elevation),...data.earth.map(s=>s.elevation))-1,high=Math.max(5,mask,...data.sun.map(s=>s.elevation),...data.earth.map(s=>s.elevation))+1;
  const y=(e:number)=>170-(e-low)/(high-low)*135;const path=(values:SkySample[])=>values.map((s,i)=>`${i?'L':'M'}${40+i/(values.length-1)*400},${y(s.elevation)}`).join(' ');
  return <><svg viewBox="0 0 480 205" role="img" aria-label="Sun and Earth elevation through the selected date interval, with horizon and assumed obstruction mask"><rect x="40" y={y(0)} width="400" height={170-y(0)} fill="#19212b"/><line x1="40" x2="440" y1={y(0)} y2={y(0)} stroke="#b6c1cb" strokeDasharray="3 4"/><text x="42" y={y(0)-5} fill="#c9d5df" fontSize="9">0° geometric horizon</text>{[low,high].map(v=><text key={v} x="3" y={y(v)+3} fill="#a3bacd" fontSize="10">{v.toFixed(1)}°</text>)}<line x1="40" x2="440" y1={y(mask)} y2={y(mask)} stroke="#b6a5ec" strokeDasharray="7 4"/><path d={path(data.sun)} fill="none" stroke="#f1cd78" strokeWidth="2.5"/><path d={path(data.earth)} fill="none" stroke="#78cfe8" strokeWidth="2.5"/><line x1={40+index/(data.sun.length-1)*400} x2={40+index/(data.sun.length-1)*400} y1="30" y2="170" stroke="#c7d4de" opacity=".6"/><text x="40" y="195" fill="#a3bacd" fontSize="10">{data.start}</text><text x="440" y="195" textAnchor="end" fill="#a3bacd" fontSize="10">{data.end} UTC</text></svg><div className="sky-readout"><span className="sun-key">☀ Sun <b>{sun.elevation.toFixed(2)}° elevation</b><small>{sun.azimuth.toFixed(1)}° azimuth · {sun.elevation>mask?'above mask':'below mask'}</small></span><span className="earth-key">◉ Earth <b>{earth.elevation.toFixed(2)}° elevation</b><small>{earth.azimuth.toFixed(1)}° azimuth · {earth.elevation>mask?'above mask':'below mask'}</small></span></div></>;
}
function Result({data,mask,label}:{data:Ephemeris;mask:number;label:string}){
  const [index,setIndex]=useState(0);const site=sites.find(s=>s.id===data.siteId)!;const earthWindows=aboveHorizonWindows(data.earth,mask),sunWindows=aboveHorizonWindows(data.sun,mask);
  const download=async()=>{const {downloadReport}=await import('@/lib/pdf-report');downloadReport('NASA geometry scenario','lunaris-'+data.siteId,[{heading:site.shortName,lines:[data.start+' to '+data.end+' UTC',`Assumed mask: ${mask} degrees`,`Sun above mask: ${opportunityPercent(data.sun,mask).toFixed(1)}%`,`Earth above mask: ${opportunityPercent(data.earth,mask).toFixed(1)}%`,'NASA/JPL Horizons target-center geometry, not terrain-aware illumination or operational radio predictions.']},{heading:'Earth visibility windows',lines:earthWindows.length?earthWindows.map(w=>w.start+' to '+w.end+` (${w.hours.toFixed(1)} hours)`):['None']},{heading:'Solar windows',lines:sunWindows.length?sunWindows.map(w=>w.start+' to '+w.end+` (${w.hours.toFixed(1)} hours)`):['None']},{heading:'Sources and method',lines:['Hourly samples; crossings linearly interpolated. Observer height zero relative to reference sphere. Retrieved '+data.retrievedAt,site.sourceUrl,...data.sources]}]);};
  return <article className="planning-result"><p className="eyebrow">SCENARIO {label}</p><h3>{site.shortName}</h3><p>{data.start} → {data.end} · UTC</p><div className="opportunity-metrics"><div><b>{opportunityPercent(data.sun,mask).toFixed(1)}%</b><span>Sun center above mask</span></div><div><b>{opportunityPercent(data.earth,mask).toFixed(1)}%</b><span>Earth center above mask</span></div></div><SkyChart data={data} index={Math.min(index,data.sun.length-1)} mask={mask}/><label htmlFor={`time-${label}`}>Inspect time · {timeLabel(data.sun[index].time)} UTC</label><input id={`time-${label}`} type="range" min="0" max={data.sun.length-1} step="1" value={index} onChange={e=>setIndex(Number(e.target.value))}/><p className="chart-key">Gold: Sun · Cyan: Earth · Dashed purple: assumed mask {mask}°<br/>Azimuth runs clockwise from north (0°), through east (90°).</p>
    <details open><summary>Potential direct-to-Earth windows ({earthWindows.length})</summary><p>Earth-center geometry only. Terrain, ground-station coverage and antenna link budget are not included. Boundaries are linearly interpolated from hourly samples.</p>{earthWindows.length?<ul>{earthWindows.map(w=><li key={w.start}>{timeLabel(w.start)} → {timeLabel(w.end)} UTC <b>({w.hours.toFixed(1)} h)</b></li>)}</ul>:<p>No Earth-center elevation above the assumed mask during this interval.</p>}</details>
    <details><summary>Solar opportunities ({sunWindows.length})</summary><p>Potential exposure only: no panel efficiency, orientation, terrain shadows, eclipses or battery model. Percentages are not electrical power estimates.</p>{sunWindows.length?<ul>{sunWindows.map(w=><li key={w.start}>{timeLabel(w.start)} → {timeLabel(w.end)} UTC ({w.hours.toFixed(1)} h)</li>)}</ul>:<p>No Sun-center elevation above the assumed mask.</p>}</details>
    <details><summary>Hourly data table & provenance</summary><p>NASA/JPL Horizons · retrieved {timeLabel(data.retrievedAt)} UTC. Observer height: 0 km relative to the 1,737.4 km lunar reference sphere. Approximate research coordinates: {site.latitude}°, {site.longitude}° E.</p><a href={site.sourceUrl} target="_blank" rel="noreferrer">Research coordinate source ↗</a><div className="ephemeris-table"><table><thead><tr><th>UTC</th><th>Sun az / el (°)</th><th>Earth az / el (°)</th></tr></thead><tbody>{data.sun.map((s,i)=><tr key={s.time}><td>{timeLabel(s.time)}</td><td>{s.azimuth.toFixed(2)} / {s.elevation.toFixed(2)}</td><td>{data.earth[i].azimuth.toFixed(2)} / {data.earth[i].elevation.toFixed(2)}</td></tr>)}</tbody></table></div>{data.sources.map((url,i)=><a className="raw-source" key={url} href={url} target="_blank" rel="noreferrer">NASA raw {i===0?'Sun':'Earth'} response ↗</a>)}<pre>{data.headers.join('\n')}</pre></details><button className="planner-secondary" onClick={download}>Download scenario PDF</button>
  </article>;
}
export default function PlanningPanel(){
  const [a,setA]=useState<Scenario>({site:sites[0].id,start:'2026-11-01',end:'2026-11-08'}),[b,setB]=useState<Scenario>({site:sites[1].id,start:'2026-11-01',end:'2026-11-08'}),[mask,setMask]=useState(0),[results,setResults]=useState<Ephemeris[]|null>(null),[pending,setPending]=useState(false),[error,setError]=useState(''),[runKey,setRunKey]=useState('');
  const key=JSON.stringify([a,b]),stale=results&&key!==runKey;
  const run=async()=>{setError('');try{validateInterval(a.start,a.end);validateInterval(b.start,b.end)}catch(e){setError((e as Error).message);return}setPending(true);try{const output:Ephemeris[]=[];for(const scenario of [a,b]){const response=await fetch('/api/ephemeris?'+new URLSearchParams(scenario),{signal:AbortSignal.timeout(115000)});const data=await response.json();if(!response.ok)throw Error(data.error??'Unable to load NASA data.');output.push(data)}setResults(output);setRunKey(key)}catch(e){setError(e instanceof Error?e.message:'Unable to load NASA data.')}finally{setPending(false)}};
  return <div className="planning-panel"><p className="eyebrow">SOUTH POLAR SITE & DATE PLANNING</p><h2>Find your window on the Moon.</h2><p>Compare Sun and Earth positions at two research sites - or compare two dates at the same site. Live NASA/JPL ephemerides show how close each body is to the horizon.</p><div className="planning-scenarios">{([[a,setA,'A'],[b,setB,'B']] as const).map(([s,set,label])=><fieldset disabled={pending} key={label}><legend>Scenario {label}</legend><label>Research site {label}<select value={s.site} onChange={e=>set({...s,site:e.target.value})}>{sites.map(site=><option key={site.id} value={site.id}>{site.shortName}</option>)}</select></label><label>Start date {label} · UTC<input type="date" min="2024-01-01" max="2030-12-30" value={s.start} onChange={e=>set({...s,start:e.target.value})}/></label><label>End date {label} · UTC<input type="date" min={s.start} max="2030-12-31" value={s.end} onChange={e=>set({...s,end:e.target.value})}/></label></fieldset>)}</div><p className="planner-hint">Intervals begin at 00:00 UTC and end at 00:00 UTC on the end date. Choose 1–31 days. Samples are one hour apart.</p><button className="planner-run" disabled={pending} onClick={run}>{pending?'Retrieving NASA Sun & Earth ephemerides…':'Compare sites & dates'}</button><p role="status" className="planner-hint">{pending?'Requesting both bodies for each scenario. This may take up to a minute.':''}</p>{error&&<p role="alert" className="planner-error">{error}</p>}
    <div className="planning-assumptions"><b>Geometric planning preview</b><p>These angles are relative to a flat local reference horizon, independent of the artistic 3D Moon. Local ridges and craters can block either body. This does not yet predict terrain-aware illumination, electrical power or operational radio contacts.</p><label>Assumed obstruction / elevation mask: {mask}°<input aria-label="Assumed obstruction mask" type="range" min="0" max="10" step="0.5" value={mask} onChange={e=>setMask(Number(e.target.value))}/></label><p>The constant mask is a sensitivity control, not a measured terrain horizon.</p></div>
    {stale&&<p role="status" className="planner-error">Inputs changed. Results below belong to the previous labeled scenarios; run comparison again to update.</p>}{results&&<div className="planning-results">{results.map((data,i)=><Result key={`${runKey}-${i}`} data={data} mask={mask} label={i===0?'A':'B'}/>)}</div>}
    <p className="planner-hint">Reference frame: Horizons lunar mean-Earth model; positive-east longitude. Body centers, airless apparent angles, with light-time and aberration corrections. Crossings are approximate at the one-hour sampling scale.</p><a href="https://ssd.jpl.nasa.gov/horizons/manual.html" target="_blank" rel="noreferrer">NASA/JPL Horizons methodology ↗</a>
  </div>;
}

