'use client';
import {useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {sites} from '@/lib/sites';
import {polarPoint,polarCoordinate,constrainMap} from '@/lib/polar';
import layers from '@/data/map-layers.json';
const layerGuide:Record<string,{title:string;meaning:string;low:string;high:string}>={
 sun:{title:'Sunlight average',meaning:'Share of time each location receives sunlight, averaged over an 18.6-year lunar cycle.',low:'Less sunlight',high:'Near-continuous sunlight'},
 earth:{title:'Earth visibility average',meaning:'Share of time any part of Earth’s disk is visible above local terrain, averaged over 18.6 years. Visibility does not guarantee a usable radio link.',low:'Rarely visible',high:'Visible most of the time'},
 elevation:{title:'Terrain elevation',meaning:'Surface height relative to the lunar reference sphere, in meters. The color scale clips values outside its displayed range.',low:'Lower terrain',high:'Higher terrain'},
 slope:{title:'Terrain slope',meaning:'Surface steepness in degrees from horizontal. 0° is level; larger angles are steeper.',low:'Gentler slope',high:'Steeper slope'},
};
export default function PolarMap({selectedId,onSelect,onOpenTerrain}:{selectedId:string;onSelect:(id:string)=>void;onOpenTerrain:(id:string)=>void}){
 const [requestedKind,setKind]=useState('sun'),[rawView,setView]=useState({x:0,y:-45000,span:350000}),[grid,setGrid]=useState(true),[readout,setReadout]=useState('');
 const [regionId,setRegionId]=useState('');
 const [expanded,setExpanded]=useState(false);
 const panel=useRef<HTMLElement>(null);
 useEffect(()=>{if(!expanded)return;const previous=document.activeElement as HTMLElement|null;const overflow=document.body.style.overflow;document.body.style.overflow='hidden';panel.current?.focus();const escape=(e:KeyboardEvent)=>{if(e.key==='Escape')setExpanded(false)};document.addEventListener('keydown',escape);return()=>{document.body.style.overflow=overflow;document.removeEventListener('keydown',escape);previous?.focus()}},[expanded]);
 const drag=useRef<{x:number;y:number;vx:number;vy:number}|null>(null);
 const kind=requestedKind;
 const terrain=kind==='slope'||kind==='elevation';
 const bounds=[-320000,-320000,320000,320000];
 const view=constrainMap(rawView,bounds);
 const zoom=(factor:number)=>setView(constrainMap({...view,span:view.span*factor},bounds));
 const focus=(id:string)=>{setRegionId('');const s=sites.find(s=>s.id===id)!;const p=polarPoint(s.latitude,s.longitude);setView({...p,span:terrain?16000:65000});onSelect(id)};
 const shown=layers.filter(l=>l.kind===kind), legend=shown[0], layerDescription=layerGuide[kind], unit=kind==='elevation'?' m':kind==='slope'?'°':'%';
 const regionNames:Record<string,string>={Site01:'Connecting Ridge',Site04:'Shackleton Rim',Site06:'Nobile Rim 1',Site07:'Peak near Shackleton',Site11:'de Gerlache Rim',Site23:'Malapert Massif'};
 const exploreRegion=(id:string)=>{setRegionId(id.split('_')[0]);const l=shown.find(l=>l.id===id);if(!l)return;const [left,bottom,right,top]=l.bounds;setView({x:(left+right)/2,y:-(bottom+top)/2,span:Math.max(right-left,top-bottom)*1.15})};
 const allCoverage=()=>{if(!terrain){setView({x:0,y:-45000,span:350000});return}const left=Math.min(...shown.map(l=>l.bounds[0])),bottom=Math.min(...shown.map(l=>l.bounds[1])),right=Math.max(...shown.map(l=>l.bounds[2])),top=Math.max(...shown.map(l=>l.bounds[3]));setView({x:(left+right)/2,y:-(bottom+top)/2,span:Math.max(right-left,top-bottom)*1.15})};
 const content=<section ref={panel} tabIndex={-1} className={`polar-map${expanded?' map-expanded':''}`} aria-label="NASA lunar south pole map"><div className="map-toolbar"><button onClick={()=>setExpanded(!expanded)} aria-pressed={expanded}>{expanded?'Exit fullscreen':'Fullscreen map'}</button><label>NASA map layer<select value={kind} onChange={e=>{const nextKind=e.target.value;setKind(nextKind);const nextTerrain=nextKind==='slope'||nextKind==='elevation';const nextLayer=nextTerrain&&regionId?layers.find(l=>l.kind===nextKind&&l.id.startsWith(regionId+'_')):undefined;if(nextLayer){const [left,bottom,right,top]=nextLayer.bounds;setView({x:(left+right)/2,y:-(bottom+top)/2,span:Math.max(right-left,top-bottom)*1.15})}else{const point=polarPoint(sites.find(s=>s.id===selectedId)!.latitude,sites.find(s=>s.id===selectedId)!.longitude);setView({...point,span:nextTerrain?16000:350000})}}}><option value="sun">Sunlight average</option><option value="earth">Earth visibility average</option><option value="elevation">Terrain elevation</option><option value="slope">Terrain slope</option></select></label>{terrain&&<label>Explore terrain region<select aria-label="Explore terrain region" value={shown.find(l=>l.id.startsWith(regionId+'_'))?.id||''} onChange={e=>exploreRegion(e.target.value)}><option value="" disabled>Choose a NASA coverage area</option>{shown.map(l=><option key={l.id} value={l.id}>{regionNames[l.id.split('_')[0]]||l.id.split('_')[0]}</option>)}</select></label>}<button onClick={()=>zoom(.5)} aria-label="Zoom map in">+</button><button onClick={()=>zoom(2)} aria-label="Zoom map out">−</button><button onClick={()=>focus(selectedId)}>Focus site</button><button onClick={allCoverage}>{terrain?'All terrain coverage':'Reset map'}</button><label><input type="checkbox" checked={grid} onChange={e=>setGrid(e.target.checked)}/> Grid</label></div>
 <div className="map-canvas"><svg viewBox={`${view.x-view.span/2} ${view.y-view.span/2} ${view.span} ${view.span}`} tabIndex={0} role="application" aria-label="Polar map. Drag to pan. Use plus and minus to zoom and arrow keys to pan." style={{touchAction:'none'}} onKeyDown={e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','=','-'].includes(e.key)){e.preventDefault();if(e.key==='+'||e.key==='=')zoom(.5);else if(e.key==='-')zoom(2);else setView(constrainMap({...view,x:view.x+(e.key==='ArrowLeft'?-.15:e.key==='ArrowRight'?.15:0)*view.span,y:view.y+(e.key==='ArrowUp'?-.15:e.key==='ArrowDown'?.15:0 )*view.span},bounds))}}} onWheel={e=>zoom(e.deltaY>0?1.15:1/1.15)} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);drag.current={x:e.clientX,y:e.clientY,vx:view.x,vy:view.y}}} onPointerMove={e=>{const rect=e.currentTarget.getBoundingClientRect();const scale=view.span/Math.min(rect.width,rect.height);if(drag.current){const d=drag.current;setView(constrainMap({...view,x:d.vx-(e.clientX-d.x)*scale,y:d.vy-(e.clientY-d.y)*scale},bounds))}else{const p=polarCoordinate(view.x+(e.clientX-rect.left-rect.width/2)*scale,view.y+(e.clientY-rect.top-rect.height/2)*scale);setReadout(`${Math.abs(p.latitude).toFixed(3)}° S · ${p.longitude.toFixed(3)}° E`)}}} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null}>
 <rect x={view.x-view.span/2} y={view.y-view.span/2} width={view.span} height={view.span} fill="#172536"/>
 {terrain&&<><defs><pattern id="terrain-gaps" width={view.span/35} height={view.span/35} patternUnits="userSpaceOnUse"><path d={`M 0 0 L ${view.span/35} ${view.span/35}`} stroke="#34495b" strokeWidth={view.span/1000}/></pattern></defs><rect x={view.x-view.span/2} y={view.y-view.span/2} width={view.span} height={view.span} fill="url(#terrain-gaps)"/></>}
 {shown.map(l=><image key={l.id} href={l.url} x={l.bounds[0]} y={-l.bounds[3]} width={l.bounds[2]-l.bounds[0]} height={l.bounds[3]-l.bounds[1]}/>)}
 {terrain&&shown.filter(l=>['Site06','Site07','Site11'].some(id=>l.id.startsWith(id+'_'))).map(l=>{const name=regionNames[l.id.split('_')[0]],x=(l.bounds[0]+l.bounds[2])/2,y=-(l.bounds[1]+l.bounds[3])/2;return <g key={`label-${l.id}`} pointerEvents="none"><circle cx={x} cy={y} r={view.span/240} fill="#f5cf78" stroke="#07131b" strokeWidth={view.span/1800}/><text x={x+view.span/90} y={y-view.span/90} fill="white" stroke="#09111c" strokeWidth={view.span/1000} paintOrder="stroke" fontSize={view.span/65}>{name}</text></g>})}
 {grid&&<g fill="none" stroke="#d8f2ff" opacity=".35" strokeWidth={view.span/1300}>{[-89,-88,-86,-84,-80,-75].map(lat=><circle key={lat} r={Math.abs(polarPoint(lat,0).y)}/>)}{Array.from({length:12},(_,i)=>{const p=polarPoint(-70,i*30);return <line key={i} x1="0" y1="0" x2={p.x} y2={p.y}/>})}</g>}
 <text x="0" y="0" fill="white" fontSize={view.span/55}>90° S</text>
 {sites.map(s=>{const p=polarPoint(s.latitude,s.longitude);return <g key={s.id} role="button" tabIndex={0} aria-label={`Select ${s.shortName} on map`} onPointerDown={e=>e.stopPropagation()} onDoubleClick={()=>onOpenTerrain(s.id)} onClick={()=>onSelect(s.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();focus(s.id)}}}><circle cx={p.x} cy={p.y} r={view.span/70} fill={s.id===selectedId?'#fff':'#ffce73'} stroke="#09111c" strokeWidth={view.span/350}/><text textAnchor={s.id==='connecting-ridge'?'end':'start'} x={p.x+(s.id==='connecting-ridge'?-1:1)*view.span/45} y={p.y+(s.id==='shackleton-rim'?1:-1)*view.span/50} fill="white" stroke="#09111c" strokeWidth={view.span/500} paintOrder="stroke" fontSize={view.span/50}>{s.shortName}</text></g>})}
 </svg></div><div className="map-footer"><span>{readout||'Drag to pan · Scroll to zoom · Keyboard arrows to pan'}</span><span>Map width {(view.span/1000).toFixed(0)} km (projected)</span></div><div className="map-layer-meaning" aria-live="polite"><b>{layerDescription.title}</b><p>{layerDescription.meaning}</p></div><div className="map-legend" role="img" aria-label={`${layerDescription.title}: ${legend.min}${unit} to ${legend.max}${unit}`}><span>{legend.min}{unit}</span><i/><span>{legend.max}{unit}</span></div><div className="map-legend-endpoints" aria-hidden="true"><span>{layerDescription.low}</span><span>{layerDescription.high}</span></div><p>Click a site to select it. Double-click its marker or name to open 3D terrain.</p><button onClick={()=>onOpenTerrain(selectedId)}>Open selected 3D terrain</button><div className="map-sites">{sites.map(s=><button key={s.id} aria-pressed={s.id===selectedId} onDoubleClick={()=>onOpenTerrain(s.id)} onClick={()=>focus(s.id)}>{s.shortName}</button>)}</div><p>NASA LOLA / PGDA · Lunar south-polar stereographic · 0° E points up. Pan freely between sites within the polar region. Elevation and slope cover six local NASA regions; hatched areas have no downloaded terrain data. Choose Explore terrain region to visit additional areas, or All terrain coverage to see every patch. Region views use raster centers and do not change the mission reference site.</p><p>{kind==='sun'||kind==='earth'?'Historical averages, not a selected-date forecast. Source: 120 m/pixel; map preview ~596 m/pixel.':`Source: 5 m/pixel; map previews ${Math.round(Math.min(...shown.map(l=>l.displayResolution)))} to ${Math.round(Math.max(...shown.map(l=>l.displayResolution)))} m/pixel. Colors are clipped to the displayed legend range.`} Research pins are approximate published points.</p><a href={`https://pgda.gsfc.nasa.gov/products/${kind==='sun'||kind==='earth'?'69':'78'}`} target="_blank" rel="noreferrer">NASA layer source ↗</a></section>;
 return expanded?createPortal(content,document.body):content;
}


